// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: transaction.proto

package transactionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTransactionsRequest) Reset() {
	*x = GetAllTransactionsRequest{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTransactionsRequest) ProtoMessage() {}

func (x *GetAllTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

type TransactionItem struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Id                               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Company                          string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Documents                        string                 `protobuf:"bytes,5,opt,name=documents,proto3" json:"documents,omitempty"`
	LinkToIndividualEntrepreneurship string                 `protobuf:"bytes,6,opt,name=linkToIndividualEntrepreneurship,proto3" json:"linkToIndividualEntrepreneurship,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *TransactionItem) Reset() {
	*x = TransactionItem{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItem) ProtoMessage() {}

func (x *TransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItem.ProtoReflect.Descriptor instead.
func (*TransactionItem) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransactionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionItem) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *TransactionItem) GetDocuments() string {
	if x != nil {
		return x.Documents
	}
	return ""
}

func (x *TransactionItem) GetLinkToIndividualEntrepreneurship() string {
	if x != nil {
		return x.LinkToIndividualEntrepreneurship
	}
	return ""
}

type GetAllTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionItem     `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTransactionsResponse) Reset() {
	*x = GetAllTransactionsResponse{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTransactionsResponse) ProtoMessage() {}

func (x *GetAllTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllTransactionsResponse) GetTransactions() []*TransactionItem {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\vtransaction\"\x1b\n" +
	"\x19GetAllTransactionsRequest\"\xdb\x01\n" +
	"\x0fTransactionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12\x1c\n" +
	"\tdocuments\x18\x05 \x01(\tR\tdocuments\x12J\n" +
	" linkToIndividualEntrepreneurship\x18\x06 \x01(\tR linkToIndividualEntrepreneurship\"^\n" +
	"\x1aGetAllTransactionsResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.transaction.TransactionItemR\ftransactions2{\n" +
	"\x12TransactionService\x12e\n" +
	"\x12GetAllTransactions\x12&.transaction.GetAllTransactionsRequest\x1a'.transaction.GetAllTransactionsResponseB+Z)internal/grpc/transactionpb;transactionpbb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transaction_proto_goTypes = []any{
	(*GetAllTransactionsRequest)(nil),  // 0: transaction.GetAllTransactionsRequest
	(*TransactionItem)(nil),            // 1: transaction.TransactionItem
	(*GetAllTransactionsResponse)(nil), // 2: transaction.GetAllTransactionsResponse
}
var file_transaction_proto_depIdxs = []int32{
	1, // 0: transaction.GetAllTransactionsResponse.transactions:type_name -> transaction.TransactionItem
	0, // 1: transaction.TransactionService.GetAllTransactions:input_type -> transaction.GetAllTransactionsRequest
	2, // 2: transaction.TransactionService.GetAllTransactions:output_type -> transaction.GetAllTransactionsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
