// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/userservice.proto

package userservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserRequest) Reset() {
	*x = NewUserRequest{}
	mi := &file_proto_userservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserRequest) ProtoMessage() {}

func (x *NewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserRequest.ProtoReflect.Descriptor instead.
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_userservice_proto_rawDescGZIP(), []int{0}
}

func (x *NewUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NewUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NewUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *NewUserRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type NewUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserResponse) Reset() {
	*x = NewUserResponse{}
	mi := &file_proto_userservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserResponse) ProtoMessage() {}

func (x *NewUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserResponse.ProtoReflect.Descriptor instead.
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_userservice_proto_rawDescGZIP(), []int{1}
}

func (x *NewUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NewUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NewUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_proto_userservice_proto protoreflect.FileDescriptor

const file_proto_userservice_proto_rawDesc = "" +
	"\n" +
	"\x17proto/userservice.proto\x12\vuserservice\"x\n" +
	"\x0eNewUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\"\\\n" +
	"\x0fNewUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId2V\n" +
	"\vUserService\x12G\n" +
	"\n" +
	"CreateUser\x12\x1b.userservice.NewUserRequest\x1a\x1c.userservice.NewUserResponseB+Z)internal/grpc/userservicepb;userservicepbb\x06proto3"

var (
	file_proto_userservice_proto_rawDescOnce sync.Once
	file_proto_userservice_proto_rawDescData []byte
)

func file_proto_userservice_proto_rawDescGZIP() []byte {
	file_proto_userservice_proto_rawDescOnce.Do(func() {
		file_proto_userservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userservice_proto_rawDesc), len(file_proto_userservice_proto_rawDesc)))
	})
	return file_proto_userservice_proto_rawDescData
}

var file_proto_userservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_userservice_proto_goTypes = []any{
	(*NewUserRequest)(nil),  // 0: userservice.NewUserRequest
	(*NewUserResponse)(nil), // 1: userservice.NewUserResponse
}
var file_proto_userservice_proto_depIdxs = []int32{
	0, // 0: userservice.UserService.CreateUser:input_type -> userservice.NewUserRequest
	1, // 1: userservice.UserService.CreateUser:output_type -> userservice.NewUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_userservice_proto_init() }
func file_proto_userservice_proto_init() {
	if File_proto_userservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userservice_proto_rawDesc), len(file_proto_userservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userservice_proto_goTypes,
		DependencyIndexes: file_proto_userservice_proto_depIdxs,
		MessageInfos:      file_proto_userservice_proto_msgTypes,
	}.Build()
	File_proto_userservice_proto = out.File
	file_proto_userservice_proto_goTypes = nil
	file_proto_userservice_proto_depIdxs = nil
}
